# Generated by Django 3.2.3 on 2021-05-24 03:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Location name', max_length=64, unique=True, verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Location',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Material name', max_length=64, unique=True, verbose_name='Material')),
            ],
            options={
                'verbose_name': 'Material',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Departure date')),
                ('arrival_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Arrival date')),
                ('capacity', models.FloatField(help_text='Vehicle Capacity', verbose_name='Capacity')),
                ('consumption', models.FloatField(help_text='Vehicle consumption', verbose_name='Consumption')),
                ('state', models.CharField(choices=[('loading', 'Loading'), ('inprogress', 'In progress'), ('done', 'Done')], default='loading', max_length=64)),
                ('arrival_location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_location', to='operation.location', verbose_name='Arrival location')),
                ('departure_location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_location', to='operation.location', verbose_name='Departure location')),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.driver', verbose_name='Driver')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.vehicle', verbose_name='Vehicle')),
            ],
            options={
                'verbose_name': 'Travel',
                'ordering': ('departure_date',),
            },
        ),
    ]
