# Generated by Django 3.2.3 on 2021-05-24 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Driver name', max_length=64, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Driver',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text='Vehicle brand', max_length=64, verbose_name='Brand')),
                ('model', models.CharField(help_text='Vehicle model', max_length=64, verbose_name='Model')),
                ('plate', models.CharField(help_text='Vehicle plate', max_length=64, unique=True, verbose_name='Plate')),
                ('capacity', models.FloatField(help_text='Vehicle Capacity', verbose_name='Capacity')),
                ('consumption', models.FloatField(help_text='Vehicle consumption', verbose_name='Consumption')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'ordering': ('plate',),
            },
        ),
    ]
